// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/it-moom/moom-roles/app/roles/service/internal/biz"
	"github.com/it-moom/moom-roles/app/roles/service/internal/conf"
	"github.com/it-moom/moom-roles/app/roles/service/internal/data"
	"github.com/it-moom/moom-roles/app/roles/service/internal/server"
	"github.com/it-moom/moom-roles/app/roles/service/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	client := data.NewRd(confData, logger)
	dataData, cleanup, err := data.NewData(db, client, logger)
	if err != nil {
		return nil, nil, err
	}
	rolesRepo := data.NewUserRepo(dataData, logger)
	rolesUseCase := biz.NewRolesUseCase(rolesRepo, logger)
	rolesService := service.NewRolesService(rolesUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, logger, rolesService)
	grpcServer := server.NewGRPCServer(confServer, logger, rolesService)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
