version: '3'
services:
  mysql:
    restart: always
    image: mysql/mysql-server
    container_name: moom-role-mysql
    ports:
      - 3307:3306   # 使用3307是因为防止本机默认启动mysql而抛出端口占用错误
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "password"   # defaultUser : root
      MYSQL_DATABASE: "moom-role"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      # --skip-name-resolve
      # --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
    volumes:
      - ./docker-db:/var/lib/mysql
  redis:
    container_name: moom-role-redis
    image: redis
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports: 
      - 6379:6379
    volumes:
      - ./docker/redis/redis_data:/data/
      - ./docker/redis/redis_logs:/var/log/redis/
      - ./docker/redis/redis_conf:/data/redis/
    command: redis-server /data/redis/redis.conf
